### ISSUE TITLE
Click again on resulted text is not working unless i click somewhere else.

### ISSUE THREAD

**Issue by sarojekka** [digaev/jQuery-timeDurationPicker#5]

**Comment by sarojekka** [comment]
Once I selected duration and it shows on textbox.  Click again is not happening unless I click some where else and comeback.

**Comment by digaev** [comment]
Could you provide an example of your html/js so I can reproduce it? Also, check out this page https://digaev.github.io/jquery-time-duration-picker/

Expected behavior:

* Click on input
* The widget will popup
* Select duration
* Click "OK"
* Text will be changed
* If you click on input  again, the widget should popup

**Comment by sarojekka** [comment]
I am using MVC razor view. Everything in expected behavior is working fine except the last step. 
I have click another place and come back then it works
 HTML:
<div><input type="radio" name="radio-2" id="radio-2" /> <label for="radio-2"> @LocalizedString.Portal_Label_DeleteIfUnusedFor</label> 
                         <input id="duration" type="text" readonly="readonly"  />
                        <input id="seconds" type="hidden" value="@Model.ExpireIfInactiveDuration.Seconds" />
                </div>

Script
 jQuery(function () {
        jQuery('#duration').timeDurationPicker({
            hours: false,
            minutes: false,
            seconds: false,
            defaultValue: function () {
                return jQuery('#seconds').val();
            },
            onSelect: function (element, seconds, duration) {
                jQuery('#seconds').val(seconds);
                jQuery('#duration').val(duration);
            }
        });

 });

**Comment by digaev** [comment]
Well, the javascript you've shown looks good. Does it works as expected on demo page? For now, it seems like there is some compatibility issue between jquery and razer, or perhaps the reason in your html, can't say more since I can't reproduce it in your eco-system.

If you fix it, please, let me know or just create a pull request.

**Comment by digaev** [comment]
Try to add this line(s) to `onSelect` handler:
```js
onSelect: function (element, seconds, duration) {
  jQuery('#seconds').val(seconds);
  jQuery('#duration').val(duration);
  
  this._content.button.blur();
  // this._content.div.blur(); // and probably this one
}
```
This should make widget to lost focus. Looks ugly, but may help.

**Comment by sarojekka** [comment]
The demo is working fine. 
Blur didn't work.  Just moving away doesn't work, I have to click somewhere else and then come back.

**Comment by sarojekka** [comment]
adding below worked
jQuery('#duration').blur();
